name: Continuous integration

on:
  push:
    branches:
      - main
      - release-**
  pull_request:
    branches:
      - '**'
  release:
    types: [released]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        qgis_version: [stable, '3.44', 'latest']
    env:
      QGIS_TEST_VERSION: ${{ matrix.qgis_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Test on QGIS
        run: docker compose -f .docker/docker-compose.yml run -e "PGHOST=postgres" qgis /usr/src/.docker/run-docker-tests.sh

  release:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REF: ${{ github.ref }}
    if: ${{ github.event_name == 'release' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install qtbase5-dev qttools5-dev-tools
          sudo pip install qgis-plugin-ci
      - name: Release
        run: |
          qgis-plugin-ci release ${GITHUB_REF##*/}
      - name: Get version number
        id: v
        run: |
          export VERSION_NUMBER=${GITHUB_REF/refs\/tags\/}
          echo $VERSION_NUMBER > VERSION
          echo "::set-output name=VERSION::${VERSION_NUMBER}"
      - name: 🚀 Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: urkataster_tools.${{ steps.v.outputs.VERSION }}.zip
          asset_name: urkataster_tools.${{ steps.v.outputs.VERSION }}.zip
          asset_content_type: application/zip

  documentation:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REF: ${{ github.ref }}
    if: ${{ github.event_name == 'release' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Checkout Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python requirements and playwright
        run: |
          cd docs
          pip install -r requirements.txt
          playwright install

      - name: Get version number
        id: v
        run: |
          export VERSION_NUMBER=${GITHUB_REF/refs\/tags\/}
          echo $VERSION_NUMBER > VERSION
          echo "::set-output name=VERSION::${VERSION_NUMBER}"

      - name: Build documentation
        run: |
          cd docs
          mkdocs build
          mv site/documentation.pdf documentation.${{ steps.v.outputs.VERSION }}.pdf

      - name: 🚀 Upload PDF to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: docs/documentation.${{ steps.v.outputs.VERSION }}.pdf
          asset_name: documentation.${{ steps.v.outputs.VERSION }}.pdf
          asset_content_type: application/pdf
